### ISSUE TITLE
Column start (x) greater than line length (y) error in Atom

### ISSUE THREAD

**Issue by kachkaev** [stylelint/stylelint#1409]
Looks like the coordinates for errors are not always correct (value for `col` is greater than expected). Here's an example (`client/main.less`):

```less
.class {
  .mixin();
  .mixin2;
}
```

```bash
$ stylelint --syntax less client/main.less

client/main.less
 2:13  ✖  Unexpected extra semicolon   no-extra-semicolons
 3:12  ✖  Unexpected extra semicolon   no-extra-semicolons
```

Instead of `2:13` and `3:12`, I was expecting to see `2:12` and `3:11` (or even `2:11` and `3:12`?). Because there are no characters at `2:13` and `3:12`, Atom fires an exception:

```
Error: Column start (11) greater than line length (10)
Error: Column start (11) greater than line length (10)
    at Object.rangeFromLineNumber (/home/[username]/.atom/packages/linter-stylelint/node_modules/atom-linter/lib/index.js:181:11)
    at /home/[username]/.atom/packages/editorconfig/node_modules/lazy-req/index.js:20:26
    at createRange (/home/[username]/.atom/packages/linter-stylelint/lib/index.js:65:10)
    at /home/[username]/.atom/packages/linter-stylelint/lib/index.js:110:14
    at Array.map (native)
    at stylelint.lint.then.error.type (/home/[username]/.atom/packages/linter-stylelint/lib/index.js:104:38)
```

`.stylelintrc`:
```json
{
  "extends": "stylelint-config-standard",
  "rules": {
  }
}
```
Stylelint v6.5.1

**Comment by evilebottnawi** [comment]
@kachkaev maybe duplicate https://github.com/stylelint/stylelint/issues/1389

**Comment by davidtheclark** [comment]
Yes, I think this is the same fundamental issue as https://github.com/stylelint/stylelint/issues/1389, so I'll mark it blocked (by less parser changes).

**Comment by jeddy3** [comment]
@kachkaev Please consider helping upstream in `postcss-less` if you'd like to see this issue resolved.

**Comment by kachkaev** [comment]
Hi guys,
It seems like the problem is solved upstream. Could you please update your dependencies and issue a new release?

**Comment by jeddy3** [comment]
@kachkaev Can you send us a PR with the updated dependency (in the `package.json`), along with a Less specific test for `no-extra-semicolons` please? i.e. putting something like this at the bottom of the of the `no-extra-semicolons/__tests__/index.js` file:

```js
testRule(rule, {
  ruleName,
  syntax: "less",
  config: [true],

  accept: [{
    code: ".class {<code\n  that\n  \n  passes>\n}",
  }],

  reject: [{
    code: ".class {<code\n  that\n  \n  fails\n  in\n  one\n  place>\n}",
    message: messages.rejected,
    line: 2,
    column: 11,
  }],
})
```

I just realised I don't know enough about the Less syntax to know what *the expected behaviour* is here e.g. are semicolons *required* after mixins calls? Looking through the upstream fix gives me the impression that they aren't, but the Less documentation has semicolons after mixin calls.

Once we have tests showing that things are working as expected, we'll be able to do a release for you.

**Comment by webschik** [comment]
Hi guys!
Try to use `postcss-less` *v0.13.0*, I've fixed some bugs, now you should get the right position of semicolon.

**Comment by kachkaev** [comment]
Great @webschik!

Would it be possible for you to make that PR @jeddy3 asks for? I'm sure you know LESS syntax far better than me so will be able to add a few nice examples to the tests. I'm guess there is more than just one accept and reject case to test!

**Comment by jeddy3** [comment]
@kachkaev `postcss-less` was updated to `0.13` in our latest release (`6.7.0`). Do you want to see if that works for you? If it does work, we'd still appreciate tests so that any regressions can be caught.

**Comment by webschik** [comment]
Hi guys! 

Sorry, I will try to add some tests later, now I don't have much time :(

**Comment by kachkaev** [comment]
Thanks a lot @jeddy3! I temporary removed stylelint from my project's dependencies because too many `node_modules` make meteor slow. I'll let you know if there are any errors once I enable it again!

**Comment by evilebottnawi** [comment]
@kachkaev use `devDependencies` for `stylelint`.

**Comment by kachkaev** [comment]
@evilebottnawi I do. Looks like Meteor touches them too on refresh. https://github.com/meteor/meteor/issues/7008 Build times become much longer so even for a tiny change in a stylesheet one has to wait for 10+ seconds. I tried to overcome this but then just gave up and removed all linters.

**Comment by kachkaev** [comment]
I'm afraid the issue remains. Will produce a MWE after lunch.

**Comment by evilebottnawi** [comment]
@kachkaev try to add failing tests in `postcss-less`

**Comment by kachkaev** [comment]
MWE: https://github.com/kachkaev/stylelint-less-issue-1409

Not sure I'll be able to add tests today - sorry.

**Comment by evilebottnawi** [comment]
@kachkaev thank I will try to deal with this issue this week, if I suddenly held up a ping me here

**Comment by evilebottnawi** [comment]
@kachkaev @jeddy3 i think it is bug inside postcss-less.
I am parse:
```less
.test4 {
  .mixin();
  background: red;
}
```
And get(`root.nodes[0].nodes` - we see inside first `Rule`):
```shell
[ Rule {
    raws: { before: '\n', between: '', after: '' },
    type: 'rule',
    parent: 
     Rule {
       raws: [Object],
       type: 'rule',
       nodes: [Circular],
       parent: [Object],
       source: [Object],
       selector: 'a',
       lastEach: 1,
       indexes: {} },
    source: { start: [Object], input: [Object], end: [Object] },
    selector: '.mixin()',
    params: '()',
    ruleWithoutBody: true,
    extendRule: false,
    important: false,
    lastEach: 1,
    indexes: { '1': 0 } },
  Declaration {
    raws: { before: ';\n', between: ':' },
    type: 'decl',
    parent: 
     Rule {
       raws: [Object],
       type: 'rule',
       nodes: [Circular],
       parent: [Object],
       source: [Object],
       selector: 'a',
       lastEach: 1,
       indexes: {} },
    source: { start: [Object], input: [Object], end: [Object] },
    prop: 'background',
    value: 'red' } ]
```
Mixin don't have right parse values:
Incorrectly (we have):
```shell
raws: { before: '\n', between: '', after: '' },
```
Correctly:
```shell
raws: { before: '\n', between: '', semicolon: true}
```

Also in next `Decl` we have incorrect values.
Incorrectly (we have):
```shell
raws: { before: ';\n', between: ':' }
```
Correctly:
```shell
raws: { before: '\n', between: ':' }
```

**Comment by evilebottnawi** [comment]
Done in https://github.com/webschik/postcss-less/issues/49#issuecomment-230703316, need testing guys

**Comment by ntwb** [comment]
@kachkaev can you please try PostCSS-Less v`0.14.0`?

Change it from `0.13.0` to `0.14.0` in your `package.json` file please

**Comment by kachkaev** [comment]
@ntwb will do this tomorrow morning – don't have the project around at the moment. Thank you!

**Comment by kachkaev** [comment]
The error no longer occurs, but some strange things are still happening around the mixins. E.g.:

Given `"declaration-block-semicolon-space-before": "never"`:
```less
.class1 {
  color: green;
  .mixin();
  .mixin2;
}

.class2 {
  color: green ; // <-Unexpected whitespace before ";" (as expected)
  .mixin() ; // <- error is missing
  .mixin2 ; // <- error is missing
}
```

Given `"declaration-block-semicolon-space-before": "always"`:
```less
.class1 {
  color: green; // <-Expected single space before ";" (as expected)
  .mixin(); // <- error is missing
  .mixin2; // <- error is missing
}

.class2 {
  color: green 
  .mixin() ;
  .mixin2 ;
}
```

**Comment by kachkaev** [comment]
One more case:

```less

.class1 {
  color: green // <- Error: expected a trailing semicolon (as expected)
}

.class2 {
  .mixin() // <- error is missing
}

.class2 {
  .mixin2 // <- error is missing
}

.class {
  color: green // Expected newline after ":" with a multi-line declaration (declaration-colon-newline-after)
  .mixin() // <- Expected indentation of 4 spaces (indentation)
  .mixin2 // <- Expected indentation of 4 spaces (indentation)

}
```

**Comment by ntwb** [comment]
@kachkaev Can you please create new issues for each of the above please

**Comment by kachkaev** [comment]
@ntwb #1607 #1608
